= How to use Git Pages?

This repository has no contents of any use. It is juts an experiment to
see, how we can make use of Git pages; how to configure it, how to link
separate but related documents, how to combine Markdown, Asciidoc and
HTML, to see how the project's Wiki coexists and cooperates with Git
Pages.

Let's try a first link to an HTML document in the same folder:
dummyHtmlDoc.html

https://dummyHtmlDoc.html[Link with absolute root^]

link:https:dummyHtmlDoc.html[Link with relative root^]

https://./dummyHtmlDoc.html[2nd Link with relative root^]

This page has been made with Asciidoc file index.asciidoc in the root of
the repository. A file readMe.asciidoc is not recognized by GitHub. We had
to rename it to index.adoc and render it as HTML locally. Then, the
index.html is uploaded to GitHub and the page is shown as expected.

So, we can either use a Markdown file or we can use Asciidoc if we to the
transformation into HTML ourselves.

Here, we have a Doxygen example:

https://petervranken.github.io/dummyRepoToEvaluateGitPages/someApplication/doc/doxygen/html/globals_func.html

link:https:./someApplication/doc/doxygen/html/globals_func.html

link:https:someApplication/doc/doxygen/html/globals_func.html

link:https://./someApplication/doc/doxygen/html/globals_func.html


