= How to use Git Pages?

This repository has no contents of any use. It is juts an experiment to
see, how we can make use of Git pages; how to configure it, how to link
separate but related documents, how to combine Markdown, Asciidoc and
HTML, to see how the project's Wiki coexists and cooperates with Git
Pages.

Let's try a first link to an HTML document in the same folder:
dummyHtmlDoc.html

https://dummyHtmlDoc.html[^] (This one doesn't work.)

link:https:dummyHtmlDoc.html[^]

link:dummyHtmlDoc.html[^]

https://./dummyHtmlDoc.html[^] (This one doesn't work.)

This page has been made with Asciidoc file index.asciidoc in the root of
the repository. A file readMe.asciidoc is not recognized by GitHub. We had
to rename it to index.adoc and render it as HTML locally. Then, the
index.html is uploaded to GitHub and the page is shown as expected.

So, we can either use a Markdown file or we can use Asciidoc if we to the
transformation into HTML ourselves.

Here, we have a Doxygen example:

https://petervranken.github.io/dummyRepoToEvaluateGitPages/someApplication/doc/doxygen/html/globals_func.html

link:https:./someApplication/doc/doxygen/html/globals_func.html[^]

link:https:someApplication/doc/doxygen/html/globals_func.html[^]

link:https://./someApplication/doc/doxygen/html/globals_func.html[^] (This
one doesn't work.)

Here, we have a Javadoc example:

https://petervranken.github.io/dummyRepoToEvaluateGitPages/someJavaApplication/doc/dataModel/index.html[^]

link:https:./someJavaApplication/doc/dataModel/index.html[^]

link:https:someJavaApplication/doc/dataModel/index.html[^]

How do relative paths in links change if
link:https:./doc/someTopic/someTopic.html[we leave the root file]? 

Is it possible to use either Markdown or Asciidoc source code to define a
page? Or d we always have to create HTML from these sources locally and
have to upload this HTML? We address to two folders, each having a readme
inside:

Markdown: link:https:./doc/aPageInMarkdown[^] (Recognized but rendering is
quite different to our local one.)

Asciidoc: link:https:./doc/aPageInAsciidoc[^] (It is not recognized :( )